devcows/hugo-universal-theme

README.md
exampleSite/config.toml

The config file tries to find 'universal' instead of 'hugo-universal-theme'.

Correct theme name in example site

---

layouts/partials/recent_posts.html

Recent blog images are too big, hiding the titles etc. 
The new code will now box up the image

hide overflow for recent blog image

---

layouts/partials/carousel.html
layouts/partials/features.html

The "weight" parameter on carousel and features data was ignored, sort by it in the appropriate templates.

Sort features and carousel by data "weight"

---

layouts/partials/features.html

The current template puts all the features into a single bootstrap row.
This should have a separate row per 3 items which is what this PR addresses.
Also address when there is not an un-even number of rows.

Allow 3 sets of features per row.

---

README.md

After fumbling around for a bit, I realized that `email` had to be in `[params]`. This tiny content edit just helps make that clearer for Hugo noobies.

Contact form email in params for clarity

---

layouts/partials/features.html
layouts/partials/footer.html
layouts/partials/recent_posts.html
layouts/partials/testimonials.html

Enables markdown on the following landing page texts:
- Feature descriptions
- About us (footer)
- Contact address (footer)
- Recent posts subtitle
- Testimonials subtitle and texts

Enable markdown formatting on landing page descriptions (fixes #59)

---

layouts/partials/scripts.html

Use equality to empty string rather than isset when using the api key.
Reference : https://discuss.gohugo.io/t/solved-how-to-check-if-a-parameter-exists-in-config-toml-not-under-params/5569

Correctly apply maps API Key

---

README.md
exampleSite/config.toml
layouts/index.html
layouts/partials/top.html

This adds the official top bar typically used to include contact information
and social links.
- Ability to enable/disable the top bar (disabled by default)
- Ability to customize the text message
- Ability to customize the social links and icons from config.toml
- Compatible with older config.toml
- Fixes #73

Add top bar with social links from official theme

---

exampleSite/config.toml
layouts/partials/map.html
static/js/gmaps.init.js

Adding Google Maps API key with restrictive usage. It can only be used
by the demo site on the Hugo Themes showcase. This fixes the error
in the contact page when displaying the map.
Related issue: #68
URL: https://themes.gohugo.io/theme/hugo-universal-theme/
Also, this fixes the marker image path in contact page map.

Add Google Maps API Key for Hugo showcase site

---

layouts/partials/head.html

By default Hugo strips out comments, as a by effect it also strips out IE specific libs like html5shiv. To prevent those libs from being stripped the HTML is now marked as safe.
https://gohugo.io/templates/go-templates/#internet-explorer-conditional-comments-using-pipes

Marked IE specific libs as safeHTML so it's not stripped by Hugo

---

i18n/ca.yaml
i18n/de.yaml
i18n/en.yaml
i18n/es.yaml
i18n/fr.yaml
i18n/ru.yaml
layouts/404.html
layouts/_default/list.html
layouts/_default/single.html
layouts/index.html
layouts/page/single.html
layouts/partials/recent_posts.html

I found out that the article meta information prepositions (`By` and `On`) were not internationalized. So I added them to the layout files and the i18n translations. I am not quite sure about the russian and french translation.
I also fixed the language code, which now uses `.Site.LanguageCode`.
Thanks!

Improve i18n support

---

layouts/partials/widgets/search.html

Searching was not working, fixed the issue by changing form input names to be compliant with Google Search API.

Fixed search on blog

---

.travis.yml
exampleSite/config.toml

Using the `themesDir` option instead of a softlink. It solves two things:
* the softlink doesn't work on Windows.
* after checkout, new contributors can immediately do `cd exampleSite` and run `hugo serve`
First PR under the #101 umbrella.

Using the `themesDir` option instead of a softlink.

---

README.md

"Theme features" link in Table of Contents wasn't working because the created anchor name is determined by the heading -- which is "Features". Therefore, `[Features](#features)` must be used.

README.md: fix link to Features

---

static/js/front.js

issue is described in
https://github.com/devcows/hugo-universal-theme/issues/142
Reason: image height is set, when image has not been loaded yet.
Don't set height if image height is unknown.

fix for images not displayed in list

---

README.md
exampleSite/config.toml
layouts/partials/nav.html

This PR address the concerns raised in #126. Namely, it make the navbar use the logo site config parameter so that the a custom image file can be used.
The example site config and readme were also updated to document the feature.

make navbar use site param for site logo

---

layouts/partials/head.html

Missing / prevented favicon being found and updating.

Fixed favicon not updating

---

i18n/de.yaml

fix a typo and adhere to common spelling rules (e.g. duden.de)

Fix German translation

---

i18n/pt-br.yaml

In Portuguese, "posts" noun is a masculine gender, so we need to use "Mais novos" instead of "Mais novas".

fix minor issue in id "newer" for pt-br (gender of nouns)

---

README.md
exampleSite/config.toml
layouts/partials/contact.html
static/js/front.js

Please let me know if this is satisfactory.
It works for me. It is live here if you want to test.
https://www.lagobello.com/contact/

Fix formspree. Add possibility to send request through plain HTTP POST

---

layouts/partials/nav.html

Not much activity on #81, thought this might help.  An active class is applied to top-level menu items as well as the `Blog` menu item on blog posts.

Active class on top level items and blog post parent menu item

---

layouts/partials/head.html
layouts/partials/nav.html

As of Hugo 0.55, the following warning message appears when trying to build a site using this template:
```
WARN 2019/04/09 22:38:48 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
```
More info on the topic can be found here: [Hugo Themes Dont’s](https://discourse.gohugo.io/t/hugo-themes-donts/17714)

replace deprecated Page.URL with Page.Permalink

---

layouts/partials/head.html

As of Hugo 0.55, the following warning message appears when trying to build a site using this template:
```
WARN 2019/04/09 22:29:38 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
```
This pull request just follows the recommendation to use the global hugo function instead. More info can be found in [this hugo discussion thread](https://discourse.gohugo.io/t/pages-hugo-is-deprecated-as-of-0-55-0/17991).

replace deprecated Page.Hugo variable with global hugo function

---

layouts/partials/footer.html

I believe `.Site.RegularPages` is more suitable here, otherwise the `Blog` section shows up in recent posts in footer.

Use .Site.RegularPages instead of .Site.Pages for recent posts in footer

---

README.md
exampleSite/config.toml
layouts/partials/nav.html

- highlight blog section when on taxonomy sites (`/tags/*` and `/categories/*`)
- highlight home, too (same as PR #208)
The blog section is identified by its `identifier` key, which has the advantage that users can change the `name` and `url` of the blog menu item.
There is one basic assumption behind the code: There is only _one_ blog section in the whole site. I think this assumption is normally satisfied. If someone really wanted to create a site with multiple different blog sections, he/she would have to make other additional changes to this theme – which requires advanced knowledge of Hugo's internals anyway. For someone capable doing this, it should be rather trivial to also adjust the navigation partial to work as desired.

improve navigation highlighting:

---

README.md
exampleSite/config.toml
layouts/partials/footer.html

Similar to the `recent_posts.html` partial the footer currently only shows posts from the hardcoded 'blog' type.
This commit changes this to all `mainSections` of the site.

[footer] Show recent posts from all mainSections

---

layouts/partials/head.html

This replaces ~~part of~~ #237 and should fix what @thejaywhy was trying to fix here: https://github.com/devcows/hugo-universal-theme/pull/236
- It ensures that a banner image actually exists before adding any image-related meta tags.
- It only adds the keywords meta tag if at minimum 1 keyword is found. Additionally it also adds any tags specified in the content front matter as keywords (while removing any duplicates).

meta tags: check for image file existence and improve keywords generation

---

layouts/404.html
layouts/partials/nav.html

This PR replaces `.Site.BaseURL` with `"/" | relURL`. Using relative URLs is generally more portable, cf. https://github.com/devcows/hugo-universal-theme/pull/243 and https://github.com/devcows/hugo-universal-theme/pull/244
After this PR there is only one occurence left of `.Site.BaseURL`, found in `layouts/partials/widgets/search.html`.

use relative home URL

---

layouts/partials/widgets/search.html

This PR squashes the last occurence of `.Site.BaseURL` by replacing it with `"/" | absURL` (in `layouts/partials/widgets/search.html`). This should make the theme more portable. See also #247

replace site variable by absURL function

---

exampleSite/config.toml
layouts/partials/footer.html

Since we applied markify the text is not showing anymore. I rollback to safe_html because give to us more flexibility.

Avoid markdownify footer.

---

exampleSite/content/blog/migrate-from-jekyll.md
layouts/_default/list.html
layouts/_default/single.html
layouts/partials/head.html

Hide dates when date is not present.

---

exampleSite/config.toml
layouts/partials/contact.html

I'm a user of hugo-universal-theme.
Last day, I updated my web site and tested contact form, then I got a email from Formspree that title is 'PLEASE UPDATE YOUR LEGACY FORMS'.
I checked Formspree website and I noticed Formspree encourage to migrate old style form to new style form.
https://help.formspree.io/hc/en-us/articles/360056076314-Phasing-out-legacy-forms-email-URLs-
Under my understanding old style form is HTML form action url with email address and new style's action url is a endpoint created by Formspree dashboard after you registered and login.
So I try to fix to Formspree new form style.
Best regards.

fixed to Formspree new form style

---

layouts/partials/contact.html

Setting
- [`type="email"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) allows clients to automatically validate the input to ensure that it's either empty or a properly-formatted e-mail address.
- [`autocomplete="email"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) allows clients to properly autocomplete the field (e-mail addresses only).

Improve e-mail field on contact page

---

exampleSite/config.toml

While TOML keys _are_ case-sensitive, [Hugo normalizes them to lower-case internally](https://discourse.gohugo.io/t/config-params-should-be-all-lowercase-or-not/5051/2), so capitalization doesn't really matter. Thus, this change is for the sake of consistency.

harmonize config key capitalization

---

README.md
exampleSite/config.toml
layouts/partials/recent_posts.html

Introduce a recent_posts.hide_summary flag to not show the contents
summary in the recent posts section.
Signed-off-by: Richard Leitner <dev@bubus.at>

Add recent posts parameter to hide summary

---

layouts/_default/list.html
layouts/_default/single.html
layouts/partials/recent_posts.html
layouts/partials/widgets/categories.html
layouts/partials/widgets/tags.html

Taxonomie pages like author, tags and categories would not work if `defaultContentLanguageInSubdir` is set to true.
Use `relLangURL` instead of `relURL` to fix.

use relLangURL for taxonomies

---

layouts/partials/nav.html

Clicking the logo in the navigation bar leads one to the main page of the default language.
Switch to `relLangURL` in the logo's `href` to switch to the main page of the currently viewed language.

switch to relLangURL in navbar logo href

---

README.md
exampleSite/data/carousel/customizable.yaml
exampleSite/data/carousel/features.yaml
layouts/partials/carousel.html

Added a .href item to look for in the md. .href can be an item in it's own right of provide an href for the entire carousel item.
This commit updated the carousel.html partial to look for the above .href in the md. If it's there it creates a link for the entire carousel owl-item. If it doesn't then buisness as usual.

Fix for issue #154 - Carousel item can be a link

---

README.md
layouts/_default/list.html

Apply the `recent_posts.hide_summary` flag introduced in https://github.com/devcows/hugo-universal-theme/pull/283 also to the default blog list.
Signed-off-by: Richard Leitner <dev@bubus.at>

Use hide_summary also for blogs list

---

.github/workflows/build.yml
.github/workflows/deploy-gh-pages.yml
.github/workflows/eslint.yml
.github/workflows/slack-notify.yml

This PR bump GitHub workflow actions to latest versions, thus avoiding deprecation warnings as seen e.g. [here](https://github.com/devcows/hugo-universal-theme/actions/runs/8147451885).

Bump GitHub workflow actions to latest versions

---

layouts/partials/footer.html

`https://bootstrapious.com/p/universal-business-e-commerce-template` returns 404:
`https://bootstrapious.com/universal-business-e-commerce-template` works:

fix: bootstrapious URL update

---

README.md
exampleSite/config.toml
layouts/_default/single.html
layouts/partials/page.html

When running example site with latest hugo version 0.123.8, a deprecation warning is printed out:
```
INFO  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0
and will be removed in a future release.
Use .Site.Config.Services.Disqus.Shortname instead.
```
This PR fixes this issue.

Fix deprecation warnings emitted by hugo

---

README.md
exampleSite/.gitignore
exampleSite/content/blog/go-is-for-lovers.md
exampleSite/content/blog/migrate-from-jekyll.md
exampleSite/hugo.toml
static/css/style.blue.css
static/css/style.default.css
static/css/style.green.css
static/css/style.marsala.css
static/css/style.pink.css
static/css/style.red.css
static/css/style.turquoise.css
static/css/style.violet.css
static/js/hpneo.gmaps.js

Fix errors thrown with latest hugo version

---

layouts/partials/headers.html
layouts/partials/scripts.html

and replaced two dead links for Ie9 compatibility with the dozens of users that for some reason are still using ie9 in 2025

Bumped to bootstrap 3.4.1 and latest fontawesome
