layouts/partials/head.html, layouts/partials/scripts.html
Change URL's to stop SSL server stopping imported scripts
=> Enable theme to be used on SSL server

README.md, exampleSite/config.toml, layouts/partials/head.html
Adds ability to configure multiple colors for the theme.
=> Adds ability to configure multiple colors for the theme

exampleSite/config.toml, layouts/partials/scripts.html
Pass in google maps api key for the mapping component on the contact us page.
Please advise if there is a better way to do this.
=> Add in support for a google maps api key.

exampleSite/config.toml, layouts/_default/list.html, layouts/_default/single.html, layouts/partials/recent_posts.html
- Fixes #37
- Default date format set to "January 2, 2006"
=> Ability to configure custom date formats

exampleSite/config.toml, layouts/partials/nav.html
In order for this to work, the menu system from
hugo is used. So instead of use .Params.menu use
menu.main.  Have a look at https://gohugo.io/extras/menus/
=> Added submenus

README.md, layouts/partials/contact.html, static/js/gmaps.init.js
When the direction attribute is configure in the config.toml the
given address is used for directions instead of longitude and latitute
=> Added directions for gmaps on pin click

layouts/partials/contact.html, layouts/partials/map.html
Put the maps into a partial file so it can be easily customized by people using the theme.
=> Put maps into partial

i18n/ca.yaml, i18n/de.yaml, i18n/en.yaml, i18n/es.yaml, i18n/ru.yaml, layouts/_default/list.html, layouts/partials/widgets/search.html
Hello,
I added missing translations. For ES and CA I'm not sure, I have translated it with google, but german and russian its correct, I'm a german native speaker and my wife russian. :)
Best regards,
Sascha
=> Missing translation completed

README.md, exampleSite/config.toml, exampleSite/content/faq.md, layouts/partials/head.html
Support keyword and description meta tags.
Support default values if not defined in the individual pages.
=> Add in support for meta tags.

i18n/ru.yaml
Taken from Google Translate, so take it with a pinch of salt.
If anyone speaks russian I'd love for a review, otherwise this is close enough for now and better than no translation.
=> add missing translation for Ru "navToggle"

static/js/front.js
Fixed travis (Javascript linter)
=> Fixed travis

layouts/partials/footer.html
This should improve accessibility.
=> Add alt tags to Recent Posts in Footer

layouts/404.html
This PR replaces hardcoded values in the `404.html` template with
appropriate Hugo variables.
=> Parameterize 404

i18n/fr.yaml
Fixed some minors spelling mistakes and some translations that makes no sense in french if you traduce word by word
=> Fix french translations

i18n/it.yaml
=> Added Italian translation

i18n/ja.yaml
My old pull request ( #138 ) has an error for Travis CI. Maybe the reason is no user name for a commit. So I send re-PR.
=> japanese added

i18n/cs.yaml
Hello,
I added the Czech language to the i18n folder
=> add Czech Language (cs)

layouts/partials/head.html
Reverts devcows/hugo-universal-theme#204
issues with old versions.
=> Revert "replace deprecated Page.Hugo variable with global hugo function"

layouts/partials/recent_posts.html
it should fix https://github.com/devcows/hugo-universal-theme/issues/229
=> Show recent posts (hugo 0.59).

README.md, exampleSite/config.toml, static/css/style.blue.css, static/css/style.default.css, static/css/style.green.css, static/css/style.marsala.css, static/css/style.pink.css, static/css/style.red.css, static/css/style.turquoise.css, static/css/style.violet.css
=> Style for header icons from Universal v2.

layouts/_default/list.html, layouts/partials/footer.html, layouts/partials/map.html, layouts/partials/nav.html, layouts/partials/recent_posts.html, layouts/partials/scripts.html, layouts/partials/widgets/categories.html, layouts/partials/widgets/tags.html
=> Updated with relURL

README.md, exampleSite/config.toml, layouts/partials/map.html, layouts/partials/scripts.html
=> Add google map enable param

package-lock.json, package.json
=> Updated eslint.

i18n/zh-tw.yaml
Add traditional chinese translation for Taiwan
=> Add zh-tw translation

i18n/ro.yaml
=> Add Romanian translation

.github/workflows/main.yml, exampleSite/config.toml
Adds action to build example git github actions to ease the start of new site from the example
=> GitHub actions deploy example to gh pages

README.md, exampleSite/config.toml, layouts/partials/carousel.html, layouts/partials/clients.html, layouts/partials/testimonials.html, static/js/front.js
=> Carousel customizable.

exampleSite/static/css/custom.css
=> PoC of custom.css

.github/workflows/linters.yml, exampleSite/content/blog/categories-post.md, layouts/_default/list.html, layouts/partials/widgets/categories.html
range over all categories in blog list and correct display name to be category
upper categories in sidebar widget to lookalike tags.
=> list all categories of an entry; upper categories in sidebar widget

README.md, exampleSite/config.toml, layouts/partials/features.html
=> Able to customize number of columns.

static/css/style.blue.css, static/css/style.default.css, static/css/style.green.css, static/css/style.marsala.css, static/css/style.pink.css, static/css/style.red.css, static/css/style.turquoise.css, static/css/style.violet.css
=> Fixed icon size.

i18n/ca.yaml, i18n/cs.yaml, i18n/da.yaml, i18n/de.yaml, i18n/en.yaml, i18n/es.yaml, i18n/fr.yaml, i18n/id.yaml, i18n/it.yaml, i18n/ja.yaml, i18n/nl.yaml, i18n/pt-br.yaml, i18n/ro.yaml, i18n/ru.yaml, i18n/sv.yaml, i18n/zh-tw.yaml, i18n/zh.yaml, layouts/_default/list.html, layouts/_default/single.html, layouts/partials/recent_posts.html
=> Able to translate month dates.

README.md, exampleSite/config.toml, layouts/partials/nav.html
=> Text alternative for logo.

README.md, exampleSite/config.toml, exampleSite/content/blog/hugo-is-for-lovers.md
=> Summary example.

README.md
Hi there,
please review and merge this update on the Readme
Ref: https://github.com/devcows/hugo-universal-theme/issues/316
=> Formspree free plan is limited - Update the Readme accordingly

exampleSite/config.toml
=> devows → devcows

README.md
=> threated → treated

exampleSite/config.toml, layouts/partials/top.html
=> Safe topbar links.

i18n/cz.yaml, i18n/de.yaml
- add Czech language translation 
- fixed month names for German
=> Translations (new cz and fixed de)

package-lock.json, package.json
https://github.com/devcows/hugo-universal-theme/security/dependabot/package-lock.json/ansi-regex/open
=> Bump ansi_regex

exampleSite/config.toml, layouts/partials/testimonials.html
https://github.com/devcows/hugo-universal-theme/issues/288#issuecomment-1021452076
=> Misspelings.

i18n/pt-pt.yaml
Full translation to European Portuguese.
=> Add European Portuguese translation

README.md, exampleSite/config.toml, layouts/partials/nav.html, static/js/front.js
closes https://github.com/devcows/hugo-universal-theme/issues/185
=> Menu as mouse over.

i18n/tr.yaml
(NB Google Translated, as I don't speak Turkish. Doing a site for a client that requires it)
=> Add Turkish i18n

layouts/page/single.html
=> Fix top bar in single pages.

layouts/partials/carousel.html, layouts/partials/clients.html, layouts/partials/features.html, layouts/partials/testimonials.html
=> Not fails when folders doesn't exist.

layouts/partials/headers.html
=> bump awesome lib.

exampleSite/config.toml
=> Adapted pagination to new hugo versions.
